### ISSUE TITLE
Finalizer is working on Developer console but not from Salesforce UI

### ISSUE THREAD

**Issue by sethuramangithub** [mitchspano/apex-trigger-actions-framework#134]
Dear MitchSpano,

This is continuation of [Issue-131](https://github.com/mitchspano/apex-trigger-actions-framework/issues/131).

**Conclusion from Issue - 131:**

The managed package trigger on opportunity will prevent the system from being able to detect when to finalize. 
Multiple triggers interfere with the context stack and the rows left to process count.

**Problem Statement:**

Regarding the above statement, we understood if there is a managed package trigger for the sobject, then Finalizer will not work. 

But when we create the opportunity record from developer console, Finalized debug is getting executed successfully.

Also the same issue (Finalizer is not called) is happening for objects having only one trigger and not part of any managed package.

**Observation in my Sandbox:**

Whenever we create record from Salesforce UI, 'Finalized' debug statement is not executed. 

But for the same object whether it has single/multiple triggers per object, It is executing succesfully when we create record through script from developer console.

Kindly let us know your suggestion.

Thanks,
Sethu.

**Comment by mitchspano** [comment]
Sethu,

This is the 3rd issue you have created on this repository for the same experienced behavior - please stop spamming the repository with repeated issues.

The trigger actions framework has nothing to do with if the record was created from the UI or the developer console - all of the trigger logic will operate the same regardless.

The finalizer is only promised to work if every sObject that has a DML operation during trigger processing is also and only using the Trigger Actions Framework.

So for example if you had a trigger on Contact which updated the parent account, then a trigger on Account which updated its children Opportunities, then all of those sObjects must use the Trigger Actions Framework for the finalizer initiated on the Contact to operate.

Here's a visualization of the context stack for the above scenario:

```
Contact. BeforeUpdate
# (recordsToProcess = Limits.getDMLRows() )

=>

Contact. AfterUpdate
Contact. BeforeUpdate

=>

Account.BeforeUpdate
Contact. AfterUpdate
Contact. BeforeUpdate

=>

Account.AfterUpdate
Account.BeforeUpdate
Contact. AfterUpdate
Contact. BeforeUpdate

=>

Opportunity.BeforeUpdate
Account.AfterUpdate
Account.BeforeUpdate
Contact. AfterUpdate
Contact. BeforeUpdate

=>

Opportunity.AfterUpdate
Opportunity.BeforeUpdate
Account.AfterUpdate
Account.BeforeUpdate
Contact. AfterUpdate
Contact. BeforeUpdate

=> 

# (Opportunity.Before and After update are inverses, so they cancel)
Account.AfterUpdate
Account.BeforeUpdate
Contact. AfterUpdate
Contact. BeforeUpdate

=> 

# (Account.Before and After update are inverses, so they cancel)
Contact. AfterUpdate
Contact. BeforeUpdate

=> 

# (Contact.Before and After update are inverses, so they cancel)
# (Stack is empty, meaning that DML processing on Trigger.New is complete)
# (Decrement recordsToProcess by Trigger.new size)
# (If recordsToProcess is 0, then it's time to finalize)
```

Multiple triggers (like one from a managed package) have non-deterministic order of execution, so depending on which one fires fist, the system can mess up the count for the number of records to process and thus fail to detect when to finalize. This could be the source of the issue you are experiencing.

The issues you are experiencing with finalizers in the Trigger Actions Framework are caused by the current state of your org, not issues with the current published state of the framework. As the author of a package, I am unable to debug the current state of your org, nor can I assist with issues related to your org's configuration. Everything is working as documented.

Finalizers are not bulletproof - they are included to show what is possible, but they are not perfect and all of this is detailed in the caveats section of the README.

**Comment by sethuramangithub** [comment]
Dear MitchSpano,

Thank you for your patience and explanation in details.

Thanks,
Sethu.
